### PR TITLE
Fix: update zwijndrecht name

### PR DESCRIPTION
**Pull request by wolfderechter**
## ID
CLBV-930

## Description

Update the zwijndrecht name from `Zwijndrecht-edit` to `Zwijndrecht`.

## How to test

Go to mock-login and verify zwijndrecht now has the right name.

### CODE REVIEW

**Review by claire-lovisa — CHANGES_REQUESTED** [review]
I think that the person and the bestuurseenheid can be in different graphs, enforcing them to be in the same one doesn't delete everything, see:
```
select * where { graph ?g { ?s ?p "Zwijndrecht-edit" }}
```

Also a note on syncs, I noticed that the wrong triple was is OP's landing zone. I then checked and found this weird name in OP QA. Might be worth updating it there (via the frontend)!

**Comment by wolfderechter** [comment]
> I think that the person and the bestuurseenheid can be in different graphs, enforcing them to be in the same one doesn't delete everything, see:
> 
> ```
> select * where { graph ?g { ?s ?p "Zwijndrecht-edit" }}
> ```
> 
> Also a note on syncs, I noticed that the wrong triple was is OP's landing zone. I then checked and found this weird name in OP QA. Might be worth updating it there (via the frontend)!

I don't have OP access on QA, only dev where it's fine. But note that the 'Zwijndrecht-edit' is in both verenigingen-loket QA and DEV

**Comment by wolfderechter** [comment]
> After double checking, it can't be changed via the frontend in OP, they have double labels in the backend in seems. Probably an error at some point. Anyways, that's a problem for an other app ;)

So should I close this PR or keep it?

**Comment by claire-lovisa** [comment]
Keep it, especially if you have that issue on multiple environment (for op it's only QA), but I still think you need to separate the graphs to remove everything!

**Review by claire-lovisa — APPROVED** [review]

**Pull request merged**
